import {test} from 'node:test';
import assert from 'node:assert/strict';
import {AppNavigation} from '../src/navigation.mjs';
function fixture(){let index=0,busy=false,closed=0,roots=0,restored=null,queue=[];const entries=[null],history={replaceState(s){entries[index]=structuredClone(s);},pushState(s){entries.splice(index+1);entries.push(structuredClone(s));index++;},back(){if(index>0)queue.push(entries[--index]);},forward(){if(index<entries.length-1)queue.push(entries[++index]);}};const nav=new AppNavigation({history,restore:r=>restored=r,closeDialog:()=>closed++,isBusy:()=>busy,onRoot:()=>roots++});const flush=()=>{while(queue.length)nav.pop(queue.shift());};return {nav,history,entries,flush,get restored(){return restored},get roots(){return roots},get closed(){return closed},set busy(value){busy=value},get index(){return index}};}
test('Android back restores internal pages and gives a root exit guard',()=>{const x=fixture(),home={view:'dashboard'},utility={view:'utility',utility:{page:'shopping'}},event={view:'utility',utility:{page:'shopping',shoppingEventId:'bbq'}};x.nav.start('owner',home);x.nav.sync(utility);x.nav.sync(event);x.nav.sync(event);assert.equal(x.entries.length,4);x.history.back();x.flush();assert.deepEqual(x.restored,utility);x.history.back();x.flush();assert.deepEqual(x.restored,home);x.history.back();x.flush();assert.equal(x.roots,1);});
test('Back closes a modal without skipping its underlying page',()=>{const x=fixture(),home={view:'subscriptions'},page={view:'bills',selected:'plan'};x.nav.start('owner',home);x.nav.sync(page);x.nav.openDialog(page);x.history.back();x.flush();assert.deepEqual(x.restored,page);assert.equal(x.nav.modal,false);x.history.back();x.flush();assert.deepEqual(x.restored,home);});
test('successful create removes modal history and retains the newly created event',()=>{const x=fixture(),list={view:'utility',utility:{page:'shopping'}},event={view:'utility',utility:{page:'shopping',shoppingEventId:'new'}};x.nav.start('owner',list);x.nav.openDialog(list);x.nav.sync(event);x.nav.dismissDialog(event);x.flush();assert.deepEqual(x.restored,event);assert.equal(x.nav.modal,false);x.history.back();x.flush();assert.deepEqual(x.restored,list);});
test('Back while saving stays on the modal and account changes ignore old history',()=>{const x=fixture(),home={view:'dashboard'};x.nav.start('owner',home);x.nav.openDialog(home);const current=x.index;x.busy=true;x.history.back();x.flush();assert.equal(x.index,current);assert.equal(x.closed,0);x.busy=false;x.nav.dismissDialog(home);x.flush();assert.equal(x.nav.modal,false);x.nav.start('member',{view:'subscriptions'});x.nav.pop({kongsipayNavigation:1,uid:'owner',route:home});assert.equal(x.nav.uid,'member');assert.deepEqual(x.nav.route,{view:'subscriptions'});});


test('search selection navigates after asynchronous modal back finishes and Back returns to source',()=>{for(const destination of [{view:'bills',selected:'youtube'},{view:'utility',utility:{spaceId:'other',page:'fund'}}]){const x=fixture(),source={view:'profile'};let opened=null;x.nav.start('owner',source);x.nav.openDialog(source);x.nav.afterDialog(()=>{opened=destination;x.nav.sync(destination);});assert.equal(opened,null);x.flush();assert.deepEqual(opened,destination);assert.deepEqual(x.nav.route,destination);assert.equal(x.nav.modal,false);assert.equal(x.entries[x.index].modal,undefined);x.history.back();x.flush();assert.deepEqual(x.restored,source);}});
test('search selection runs once and signing out cancels a pending selection',()=>{const x=fixture(),source={view:'dashboard'};let clicks=0;x.nav.start('owner',source);x.nav.openDialog(source);x.nav.afterDialog(()=>clicks++);x.nav.afterDialog(()=>clicks++);x.flush();assert.equal(clicks,1);x.nav.openDialog(source);x.nav.afterDialog(()=>clicks++);x.nav.stop();x.flush();assert.equal(clicks,1);});
