import {test} from 'node:test';import assert from 'node:assert/strict';import {monthlyOverview,reminderGroups,billTimeline,statementRows,providerAmount,collectionTotal,providerFinancials,subscriptionFinancials,financialCutoff} from '../src/premium.mjs';
const state={subscriptions:[{id:'s',name:'Plan',createdBy:'o',cycles:[{id:'oct',startDate:'2026-10-01',createdAt:1},{id:'nov',startDate:'2026-11-01',createdAt:1}]}],members:[{id:'m',name:'Member'}],charges:[{id:'oct~m',subscription:'s',cycleId:'oct',member:'m',payee:'o',amount:1000,due:'2026-10-10',period:'October'},{id:'nov~m',subscription:'s',cycleId:'nov',member:'m',payee:'o',amount:1000,due:'2026-11-10',period:'November'}],payments:[{id:'p',subscriptionId:'s',cycleId:'oct',memberUid:'m',amount:4,status:'pending',submittedBy:'m',source:'kongsipay',createdAt:2}]};
test('monthly totals exclude future bills and pending amounts from next payment',()=>{const x=monthlyOverview(state,'m','2026-10-09');assert.equal(x.available,600);assert.equal(x.pending,400);assert.equal(x.future,1000);assert.equal(x.next.cycleId,'oct');});
test('reminders only owned subscriptions, current bills and unreserved balance',()=>{assert.equal(reminderGroups(state,'m',{date:'2026-10-09'}).length,0);const g=reminderGroups(state,'o',{date:'2026-10-09'});assert.equal(g[0].total,600);assert.equal(g[0].charges.length,1);});
test('timeline and statement keep submitted amounts separate from received',()=>{assert.deepEqual(billTimeline(state,state.charges[0]).map(x=>x.kind),['created','submitted']);const r=statementRows(state,[state.charges[0]])[0];assert.equal(r.received,0);assert.equal(r.pending,400);assert.equal(r.balance,1000);});

test("provider amount is explicit, separate from member charges",()=>{assert.equal(providerAmount({totalAmount:4,perPersonAmount:4}),null);assert.equal(providerAmount({providerAmountCents:1505,totalAmount:4}),1505);assert.equal(collectionTotal({...state,charges:[{cycleId:"old",amount:400},{cycleId:"old",amount:400},{cycleId:"old",amount:400}]},"old"),1200);});

test('provider summary excludes pending, rejected, reversed and forgiven payments',()=>{const charges=['a','b','c','d','e'].map(member=>({cycleId:'apr',member,amount:400}));const payments=[{cycleId:'apr',memberUid:'a',amount:4,paid:true},{cycleId:'apr',memberUid:'b',amount:4,status:'pending'},{cycleId:'apr',memberUid:'c',amount:4,paid:true,status:'reversed'},{cycleId:'apr',memberUid:'d',amount:4,paid:true,isSedekah:true},{cycleId:'apr',memberUid:'e',amount:4,paid:true,status:'rejected'}];assert.deepEqual(providerFinancials({charges,payments},{id:'apr',providerAmountCents:1505}),{paid:1505,collected:400,difference:-1105});});
test('five confirmed RM4 shares show RM20 collected and RM4.95 surplus',()=>{const charges=['a','b','c','d','e'].map(member=>({cycleId:'apr',member,amount:400})),payments=charges.map(c=>({cycleId:'apr',memberUid:c.member,amount:4,paid:true}));assert.deepEqual(providerFinancials({charges,payments},{id:'apr',providerAmountCents:1505}),{paid:1505,collected:2000,difference:495});assert.equal(providerFinancials({charges,payments},{id:'apr'}).difference,null);});

test('subscription totals combine all active cycles and exclude superseded and other subscriptions',()=>{const sub={cycles:[{id:'a',providerAmountCents:1505},{id:'b',providerAmountCents:1000},{id:'old',superseded:true,providerAmountCents:9999}]},charges=['a','b','old','other'].map(cycleId=>({cycleId,member:'m',amount:2000})),payments=charges.map(c=>({cycleId:c.cycleId,memberUid:'m',paid:true,amount:20}));assert.deepEqual(subscriptionFinancials({charges,payments},sub),{paid:2505,collected:4000,missing:0,cycles:2,difference:1495});sub.cycles.push({id:'missing'});const x=subscriptionFinancials({charges,payments},sub);assert.equal(x.paid,2505);assert.equal(x.missing,1);assert.equal(x.difference,null);assert.equal(subscriptionFinancials({charges,payments},{cycles:[]}).difference,null);});

test('15th cutoff handles month and year boundaries',()=>{assert.equal(financialCutoff('2026-09-10'),'2026-08');assert.equal(financialCutoff('2026-09-15'),'2026-08');assert.equal(financialCutoff('2026-09-16'),'2026-09');assert.equal(financialCutoff('2026-01-01'),'2025-12');});
test('cutoff totals exclude advance collections and missing future receipts',()=>{const sub={cycles:[{id:'aug',startDate:'2026-08-01',providerAmountCents:1505},{id:'sep',startDate:'2026-09-01'},{id:'dec',startDate:'2026-12-01'}]},charges=sub.cycles.map(c=>({cycleId:c.id,member:'m',amount:2000})),payments=charges.map(c=>({cycleId:c.cycleId,memberUid:'m',paid:true,amount:20})),state={charges,payments};assert.deepEqual(subscriptionFinancials(state,sub,financialCutoff('2026-09-10')),{paid:1505,collected:2000,missing:0,cycles:1,difference:495});assert.equal(subscriptionFinancials(state,sub,financialCutoff('2026-09-16')).missing,1);assert.equal(subscriptionFinancials(state,sub).collected,6000);});
