import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initializeTestEnvironment} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,getDocs,collection,query,where} from 'firebase/firestore';
import {Repository} from '../src/repository.mjs';
import {adaptData,settlement} from '../src/model.mjs';
const enabled=process.env.RUN_FIREBASE_INTEGRATION==='1';let env;const PROJECT='demo-kongsipay';
before(async()=>{if(!enabled)return;env=await initializeTestEnvironment({projectId:PROJECT,firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});});
after(async()=>{if(env)await env.cleanup();});
beforeEach(async()=>{if(env)await env.clearFirestore();});
const user=uid=>({uid,email:uid+'@example.test',emailVerified:true,displayName:uid});
const repo=uid=>new Repository(env.authenticatedContext(uid,{email:uid+'@example.test',email_verified:true}).firestore(),user(uid));
async function seed(){await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();await Promise.all([setDoc(doc(db,'profileAccess','owner','members','member'),{subscriptionId:'legacy'}),setDoc(doc(db,'users','owner'),{uid:'owner',name:'Owner',email:'owner@example.test',createdAt:1}),setDoc(doc(db,'userLookups','member@example.test'),{uid:'member',email:'member@example.test'}),setDoc(doc(db,'users','member'),{uid:'member',name:'Member',email:'member@example.test',createdAt:1}),setDoc(doc(db,'subscriptions','legacy'),{name:'Legacy plan',createdBy:'owner',memberUids:['owner','member'],pendingEmails:[],billingType:'split',currency:'RM',createdAt:1}),setDoc(doc(db,'billingCycles','old'),{subscriptionId:'legacy',label:'Old cycle',startDate:'2026-10-01',endDate:'2026-10-25',totalAmount:24,perPersonAmount:12,createdAt:1})]);});}
test('existing profile and legacy subscription load through live listeners',{skip:!enabled},async()=>{await seed();const r=repo('member');assert.equal((await r.profile()).name,'Member');const result=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Listener timed out')),10000);r.watch(state=>{clearTimeout(timeout);resolve(state);},reject);});assert.equal(result.subscriptions[0].id,'legacy');assert.equal(result.charges.length,2);r.close();});
test('verified email invitation admits member and preserves prior membership',{skip:!enabled},async()=>{await seed();await repo('owner').invite('legacy','new@example.test');const n=repo('new');await n.profile();assert.equal(await n.acceptInvites(),1);const result=await new Promise((resolve,reject)=>n.watch(resolve,reject));assert.deepEqual(new Set(result.subscriptions[0].members),new Set(['owner','member','new']));n.close();});
test('partial payment is pending until owner approval; repeat submission is idempotent',{skip:!enabled},async()=>{await seed();const member=repo('member'),owner=repo('owner');const input={subscription:'legacy',cycleId:'old',member:'member',amount:500,method:'DuitNow',reference:'test',requestId:'partial-1'};await member.recordPayment(input);await member.recordPayment(input);const q=query(collection(owner.db,'payments'),where('subscriptionId','==','legacy'),where('cycleId','==','old'));let records=(await getDocs(q)).docs.map(d=>({...d.data(),id:d.id}));assert.equal(records.length,1);assert.equal(settlement({cycleId:'old',member:'member',amount:1200},records).balance,1200);await assert.rejects(()=>member.reviewPayment('kp_partial-1',true));await owner.reviewPayment('kp_partial-1',true);records=(await getDocs(q)).docs.map(d=>d.data());assert.equal(settlement({cycleId:'old',member:'member',amount:1200},records).balance,700);await member.recordPayment({...input,amount:700,requestId:'partial-2'});await owner.reviewPayment('kp_partial-2',true);records=(await getDocs(q)).docs.map(d=>d.data());assert.equal(settlement({cycleId:'old',member:'member',amount:1200},records).received,1200);assert.equal(records.filter(p=>p.paid&&p.amount===0).length,1);});
test('concurrent submissions cannot reserve more than outstanding balance',{skip:!enabled},async()=>{await seed();const m=repo('member');const results=await Promise.allSettled(['a','b'].map(requestId=>m.recordPayment({subscription:'legacy',cycleId:'old',member:'member',amount:800,method:'Cash',requestId})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const docs=await getDocs(query(collection(m.db,'payments'),where('subscriptionId','==','legacy'),where('cycleId','==','old')));assert.equal(docs.size,1);});
test('reject releases pending amount; non-member is blocked by repository',{skip:!enabled},async()=>{await seed();const m=repo('member');await m.recordPayment({subscription:'legacy',cycleId:'old',member:'member',amount:1200,method:'Cash',requestId:'reject'});await repo('owner').reviewPayment('kp_reject',false,'Tidak diterima');await m.recordPayment({subscription:'legacy',cycleId:'old',member:'member',amount:1200,method:'Cash',requestId:'retry'});await assert.rejects(()=>repo('stranger').recordPayment({subscription:'legacy',cycleId:'old',member:'member',amount:100,method:'Cash',requestId:'outside'}));});
test('duplicate new cycles fail and snapshot membership preserves rounded cents',{skip:!enabled},async()=>{await seed();const owner=repo('owner');await owner.createCycle('legacy',{total:1001,due:'2026-11-25'});await assert.rejects(()=>owner.createCycle('legacy',{total:1001,due:'2026-11-25'}));const cycles=(await getDocs(query(collection(owner.db,'billingCycles'),where('subscriptionId','==','legacy')))).docs.map(d=>({...d.data(),id:d.id}));assert.equal(cycles.length,2);assert.deepEqual(Object.values(cycles.find(c=>c.id!=='old').shareAmountsCents),[501,500]);});
test('registered invites add immediately; cancellation preserves other invites',{skip:!enabled},async()=>{await seed();const r=repo('owner');await r.inviteMany('legacy','member@example.test, new@example.test, another@example.test');await r.cancelInvite('legacy','new@example.test');const s=(await getDoc(doc(r.db,'subscriptions','legacy'))).data();assert.deepEqual(s.memberUids,['owner','member']);assert.deepEqual(s.pendingEmails,['another@example.test']);await assert.rejects(()=>repo('member').inviteMany('legacy','stranger@example.test'));});
test('profile QR and WhatsApp persist without overwriting identity',{skip:!enabled},async()=>{await seed();const r=repo('owner');await r.saveProfile({whatsappNo:'60123456789',qrUrl:'data:image/png;base64,aGVsbG8='});const s=(await getDoc(doc(r.db,'users','owner'))).data();assert.equal(s.name,'Owner');assert.equal(s.whatsappNo,'60123456789');});
test('bulk plan rejects overlapping periods atomically',{skip:!enabled},async()=>{await seed();const r=repo('owner');await r.createPlan('legacy',{start:'2026-11',end:'2027-01',total:1001});await assert.rejects(()=>r.createPlan('legacy',{start:'2026-12',end:'2027-03',total:1000}));const rows=await getDocs(query(collection(r.db,'billingCycles'),where('subscriptionId','==','legacy')));assert.equal(rows.size,4);});
test('bulk payment is atomic, pending and idempotent',{skip:!enabled},async()=>{await seed();const r=repo('owner');await r.createCycle('legacy',{total:2400,due:'2026-11-28'});const m=repo('member'),entries=[{subscription:'legacy',cycleId:'old',member:'member',amount:1200},{subscription:'legacy',cycleId:'legacy_2026-11',member:'member',amount:1200}];await m.recordBulk(entries,{method:'DuitNow',requestId:'bulk'});await m.recordBulk(entries,{method:'DuitNow',requestId:'bulk'});let rows=await getDocs(query(collection(r.db,'payments'),where('subscriptionId','==','legacy')));assert.equal(rows.size,2);assert.ok(rows.docs.every(s=>s.data().status==='pending'));await assert.rejects(()=>m.recordBulk(entries,{method:'Cash',requestId:'over'}));rows=await getDocs(query(collection(r.db,'payments'),where('subscriptionId','==','legacy')));assert.equal(rows.size,2);});
test('manual settlement and undo preserve audit records and restore balance',{skip:!enabled},async()=>{await seed();const r=repo('owner');await r.correctCharge('legacy','old','member',true,'manual');await r.correctCharge('legacy','old','member',true,'manual');let rows=(await getDocs(query(collection(r.db,'payments'),where('subscriptionId','==','legacy')))).docs.map(s=>s.data());assert.equal(settlement({cycleId:'old',member:'member',amount:1200},rows).received,1200);await r.correctCharge('legacy','old','member',false,'undo');rows=(await getDocs(query(collection(r.db,'payments'),where('subscriptionId','==','legacy')))).docs.map(s=>s.data());assert.equal(settlement({cycleId:'old',member:'member',amount:1200},rows).balance,1200);assert.ok(rows.every(p=>p.status==='reversed'));});
async function seedDebt(){await seed();await env.withSecurityRulesDisabled(async ctx=>{await setDoc(doc(ctx.firestore(),'subscriptions','debt'),{name:'Debt',createdBy:'owner',memberUids:['owner','member'],billingType:'hutang',pendingEmails:[]});});await repo('owner').createPlan('debt',{start:'2026-11',total:10001,installments:3,payerUid:'member'});}
test('create subscription with initial members, emoji and note then edit',{skip:!enabled},async()=>{await seed();const r=repo('owner');const id=await r.saveSubscription({name:'Debt',billingType:'hutang',memberUids:['member'],iconEmoji:'💸',description:'Initial note'});let s=(await getDoc(doc(r.db,'subscriptions',id))).data();assert.deepEqual(s.memberUids,['owner','member']);assert.equal(s.description,'Initial note');await r.saveSubscription({id,name:'Updated',iconEmoji:'📦',description:'Updated note'});s=(await getDoc(doc(r.db,'subscriptions',id))).data();assert.equal(s.name,'Updated');assert.equal(s.billingType,'hutang');await assert.rejects(()=>repo('member').saveSubscription({id,name:'Forbidden'}));});
test('partial and full forgiveness preserve cash received separately',{skip:!enabled},async()=>{await seedDebt();const r=repo('owner');await r.forgive('debt','debt_2026-11','member',1000,'f1');await r.forgive('debt','debt_2026-11','member',1000,'f1');const c=(await getDoc(doc(r.db,'billingCycles','debt_2026-11'))).data();assert.equal(c.shareAmountsCents.member,2334);await r.forgive('debt','debt_2026-11','member',2334,'f2');const ps=(await getDocs(query(collection(r.db,'payments'),where('subscriptionId','==','debt')))).docs.map(s=>s.data());const x=settlement({cycleId:'debt_2026-11',member:'member',amount:2334},ps);assert.equal(x.balance,0);assert.equal(x.received,0);});
test('refinance preserves old paid history and only moves outstanding debt',{skip:!enabled},async()=>{await seedDebt();const r=repo('owner');await repo('member').recordPayment({subscription:'debt',cycleId:'debt_2026-11',member:'member',amount:1000,method:'Cash',requestId:'part'});await r.reviewPayment('kp_part',true);await r.refinance('debt',{member:'member',forgiven:1001,start:'2027-03',installments:2,requestId:'ref'});await r.refinance('debt',{member:'member',forgiven:1001,start:'2027-03',installments:2,requestId:'ref'});const cycles=(await getDocs(query(collection(r.db,'billingCycles'),where('subscriptionId','==','debt')))).docs.map(s=>({...s.data(),id:s.id}));assert.equal(cycles.filter(c=>c.superseded).length,3);const active=cycles.filter(c=>!c.superseded);assert.equal(active.length,2);assert.equal(active.reduce((n,c)=>n+c.shareAmountsCents.member,0),8000);assert.equal((await getDoc(doc(r.db,'payments','kp_part'))).data().amount,10);await assert.rejects(()=>repo('member').recordPayment({subscription:'debt',cycleId:'debt_2026-11',member:'member',amount:100,method:'Cash',requestId:'archived'}));});
test('owner deletion removes related records and leaves other subscriptions intact',{skip:!enabled},async()=>{await seedDebt();const r=repo('owner');await assert.rejects(()=>repo('member').deleteCycle('debt','debt_2026-11'));await r.deleteCycle('debt','debt_2026-11');assert.equal((await getDoc(doc(r.db,'billingCycles','debt_2026-11'))).exists(),false);await r.deleteSubscription('debt');await env.withSecurityRulesDisabled(async ctx=>assert.equal((await getDoc(doc(ctx.firestore(),'subscriptions','debt'))).exists(),false));await env.withSecurityRulesDisabled(async ctx=>assert.equal((await getDocs(query(collection(ctx.firestore(),'billingCycles'),where('subscriptionId','==','debt')))).size,0));assert.equal((await getDoc(doc(r.db,'subscriptions','legacy'))).exists(),true);});

const proof={dataUrl:'data:image/png;base64,aGVsbG8=',name:'provider.png'};
test('owner provider proof is shared with members, protected from outsiders and member writes',{skip:!enabled},async()=>{await seed();const o=repo('owner'),m=repo('member'),stranger=repo('stranger');await o.providerPaid('legacy','old',proof,2400);assert.equal((await m.getProviderProof('old')).name,'provider.png');assert.equal((await getDoc(doc(m.db,'billingCycles','old'))).data().providerAmountCents,2400);assert.equal((await getDoc(doc(m.db,'billingCycles','old'))).data().hasProviderProof,true);await assert.rejects(()=>stranger.getProviderProof('old'));await assert.rejects(()=>m.providerPaid('legacy','old',proof,2400));await assert.rejects(()=>setDoc(doc(m.db,'providerProofs','old'),{...proof,subscriptionId:'legacy',cycleId:'old',submittedBy:'member',createdAt:Date.now()}));await assert.rejects(()=>setDoc(doc(m.db,'billingCycles','old'),{providerPaid:true},{merge:true}));});
test('transfer proof is atomic and private to payer and owner',{skip:!enabled},async()=>{await seed();const m=repo('member'),o=repo('owner');await m.recordPayment({subscription:'legacy',cycleId:'old',member:'member',amount:500,method:'Cash',requestId:'proof',proof});assert.equal((await o.getProof('kp_proof')).name,'provider.png');await assert.rejects(()=>repo('stranger').getProof('kp_proof'));await assert.rejects(()=>setDoc(doc(m.db,'paymentProofs','kp_proof'),{name:'changed'},{merge:true}));await o.reviewPayment('kp_proof',true);});
test('direct financial and directory attacks are rejected',{skip:!enabled},async()=>{await seed();const m=repo('member'),x=repo('stranger');await assert.rejects(()=>getDocs(collection(m.db,'users')));await assert.rejects(()=>getDocs(collection(m.db,'userLookups')));await assert.rejects(()=>getDocs(query(collection(x.db,'payments'),where('subscriptionId','==','legacy'))));await assert.rejects(()=>setDoc(doc(m.db,'subscriptions','legacy'),{createdBy:'member'},{merge:true}));await assert.rejects(()=>setDoc(doc(m.db,'payments','attack'),{subscriptionId:'legacy',cycleId:'old',memberUid:'member',amount:12,paid:true,isSedekah:false,status:'approved',createdAt:1}));});
