import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initializeTestEnvironment} from '@firebase/rules-unit-testing';
import {doc,getDoc,updateDoc,collection,getDocs,query,where} from 'firebase/firestore';
import {UtilityRepository} from '../src/utility-repository.mjs';
import {expenseShares,expenseBalance,fundBalance,utilityAttention} from '../src/utility-model.mjs';
test('utility shares preserve cents, balances exclude payer and confirmed members',()=>{const shares=expenseShares(1001,['a','b','c']);assert.equal(Object.values(shares).reduce((a,b)=>a+b),1001);assert.equal(expenseBalance({shares,payer:'a',settled:['a','b']}),333);assert.throws(()=>expenseShares(1,['a','a']));});
test('fund ledger and attention keep history out of active dashboard',()=>{const items=[{kind:'entry',fundId:'f',amount:1000,entryType:'contribution'},{kind:'entry',fundId:'f',amount:300,entryType:'withdrawal'},{kind:'shopping',status:'active'},{kind:'shopping',status:'done'}];assert.equal(fundBalance(items,'f'),700);assert.equal(utilityAttention(items).shopping,1);});
const enabled=process.env.RUN_FIREBASE_INTEGRATION==='1';let env;
before(async()=>{if(enabled)env=await initializeTestEnvironment({projectId:'demo-kongsipay-utility',firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});});
beforeEach(async()=>{if(env)await env.clearFirestore();});after(async()=>{if(env)await env.cleanup();});
const repo=id=>new UtilityRepository(env.authenticatedContext(id,{email:id+'@example.test',email_verified:true}).firestore(),{uid:id,email:id+'@example.test',emailVerified:true,displayName:id});
async function setup(){const owner=repo('owner'),id=await owner.createSpace('Together');await owner.invite(id,'member@example.test');const member=repo('member');await member.acceptInvites();return {owner,member,id};}
test('utility invitations are explicit; outsider cannot access or promote themselves',{skip:!enabled},async()=>{const {owner,member,id}=await setup();assert.equal((await getDoc(doc(member.db,'utilitySpaces',id))).data().memberUids.length,2);const outsider=repo('outsider');await assert.rejects(()=>getDoc(doc(outsider.db,'utilitySpaces',id)));await assert.rejects(()=>outsider.add(id,'shopping',{title:'No',quantity:'1'}));await assert.rejects(()=>updateDoc(doc(member.db,'utilitySpaces',id),{createdBy:'member'}));await assert.rejects(()=>member.invite(id,'outsider@example.test'));assert.equal(await outsider.acceptInvites(),0);});
test('shared shopping updates, expenses require payer confirmation and retain split history',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),shopping=await owner.add(id,'shopping',{title:'Milk',quantity:'2'});await member.change(shopping,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',shopping))).data().status,'done');const expense=await owner.add(id,'expense',{title:'Dinner',amount:1001,participants:['owner','member'],payer:'owner'});await assert.rejects(()=>member.change(expense,'settle','member'));await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems',expense),{amount:1}));await assert.rejects(()=>owner.change(expense,'toggle'));await owner.change(expense,'settle','member');await owner.change(expense,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',expense))).data().status,'done');});
test('fund entries atomically change balance; spending permissions, overdraft and retries checked',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),fund=await owner.add(id,'fund',{title:'Trip',target:10000});await member.fundEntry(fund,2000,'contribution','My share','one');await member.fundEntry(fund,2000,'contribution','My share','one');assert.equal((await getDoc(doc(owner.db,'utilityItems',fund))).data().balance,2000);await assert.rejects(()=>member.fundEntry(fund,100,'withdrawal','No','two'));await assert.rejects(()=>owner.fundEntry(fund,2001,'withdrawal','Too much','three'));await owner.fundEntry(fund,500,'withdrawal','Tickets','four');assert.equal((await getDoc(doc(owner.db,'utilityItems',fund))).data().balance,1500);await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems',fund),{balance:99999}));await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems','entry_one'),{amount:5000}));const rows=await getDocs(query(collection(owner.db,'utilityItems'),where('spaceId','==',id)));assert.equal(rows.size,3);});

test('concurrent fund withdrawals cannot overdraw and the live watcher stays scoped',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),fund=await owner.add(id,'fund',{title:'Shared fund',target:10000});await member.fundEntry(fund,1000,'contribution','Seed','concurrent-seed');const result=await Promise.allSettled(['a','b'].map(key=>owner.fundEntry(fund,700,'withdrawal','Use',key)));assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal((await getDoc(doc(owner.db,'utilityItems',fund))).data().balance,300);const observer=repo('member');const snapshot=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Watch timed out')),5000);observer.watch(value=>{if(value.items.some(x=>x.id===fund)){clearTimeout(timeout);resolve(value);}},reject);});assert.equal(snapshot.spaces.length,1);assert.equal(snapshot.items.find(x=>x.id===fund).balance,300);observer.close();});
