import {validateAttachment} from '../src/board-attachment.mjs';
import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initializeTestEnvironment} from '@firebase/rules-unit-testing';
import {doc,getDoc,updateDoc,collection,getDocs,query,where} from 'firebase/firestore';
import {UtilityRepository} from '../src/utility-repository.mjs';
import {expenseShares,expenseBalance,fundBalance,utilityAttention,nextTaskTurn,validUtilityDate,shoppingBulk} from '../src/utility-model.mjs';
test('utility shares preserve cents, balances exclude payer and confirmed members',()=>{const shares=expenseShares(1001,['a','b','c']);assert.equal(Object.values(shares).reduce((a,b)=>a+b),1001);assert.equal(expenseBalance({shares,payer:'a',settled:['a','b']}),333);assert.throws(()=>expenseShares(1,['a','a']));});
test('fund ledger and attention keep history out of active dashboard',()=>{const items=[{kind:'entry',fundId:'f',amount:1000,entryType:'contribution'},{kind:'entry',fundId:'f',amount:300,entryType:'withdrawal'},{kind:'shopping',status:'active'},{kind:'shopping',status:'done'}];assert.equal(fundBalance(items,'f'),700);assert.equal(utilityAttention(items).shopping,1);});
const enabled=process.env.RUN_FIREBASE_INTEGRATION==='1';let env;
before(async()=>{if(enabled)env=await initializeTestEnvironment({projectId:'demo-kongsipay-utility',firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8')}});});
beforeEach(async()=>{if(env)await env.clearFirestore();});after(async()=>{if(env)await env.cleanup();});
const repo=id=>new UtilityRepository(env.authenticatedContext(id,{email:id+'@example.test',email_verified:true}).firestore(),{uid:id,email:id+'@example.test',emailVerified:true,displayName:id});
async function setup(){const owner=repo('owner'),id=await owner.createSpace('Together');await owner.invite(id,'member@example.test');const member=repo('member');await member.acceptInvites();return {owner,member,id};}
test('utility invitations are explicit; outsider cannot access or promote themselves',{skip:!enabled},async()=>{const {owner,member,id}=await setup();assert.equal((await getDoc(doc(member.db,'utilitySpaces',id))).data().memberUids.length,2);const outsider=repo('outsider');await assert.rejects(()=>getDoc(doc(outsider.db,'utilitySpaces',id)));await assert.rejects(()=>outsider.add(id,'shopping',{title:'No',quantity:'1'}));await assert.rejects(()=>updateDoc(doc(member.db,'utilitySpaces',id),{createdBy:'member'}));await assert.rejects(()=>member.invite(id,'outsider@example.test'));assert.equal(await outsider.acceptInvites(),0);});
test('shared shopping updates, expenses require payer confirmation and retain split history',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),shopping=await owner.add(id,'shopping',{title:'Milk',quantity:'2'});await member.change(shopping,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',shopping))).data().status,'done');const expense=await owner.add(id,'expense',{title:'Dinner',amount:1001,participants:['owner','member'],payer:'owner'});await assert.rejects(()=>member.change(expense,'settle','member'));await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems',expense),{amount:1}));await assert.rejects(()=>owner.change(expense,'toggle'));await owner.change(expense,'settle','member');await owner.change(expense,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',expense))).data().status,'done');});
test('fund entries atomically change balance; spending permissions, overdraft and retries checked',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),fund=await owner.add(id,'fund',{title:'Trip',target:10000});await member.fundEntry(fund,2000,'contribution','My share','one');await member.fundEntry(fund,2000,'contribution','My share','one');assert.equal((await getDoc(doc(owner.db,'utilityItems',fund))).data().balance,2000);await assert.rejects(()=>member.fundEntry(fund,100,'withdrawal','No','two'));await assert.rejects(()=>owner.fundEntry(fund,2001,'withdrawal','Too much','three'));await owner.fundEntry(fund,500,'withdrawal','Tickets','four');assert.equal((await getDoc(doc(owner.db,'utilityItems',fund))).data().balance,1500);await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems',fund),{balance:99999}));await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems','entry_one'),{amount:5000}));const rows=await getDocs(query(collection(owner.db,'utilityItems'),where('spaceId','==',id)));assert.equal(rows.size,3);});

test('concurrent fund withdrawals cannot overdraw and the live watcher stays scoped',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),fund=await owner.add(id,'fund',{title:'Shared fund',target:10000});await member.fundEntry(fund,1000,'contribution','Seed','concurrent-seed');const result=await Promise.allSettled(['a','b'].map(key=>owner.fundEntry(fund,700,'withdrawal','Use',key)));assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal((await getDoc(doc(owner.db,'utilityItems',fund))).data().balance,300);const observer=repo('member');const snapshot=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Watch timed out')),5000);observer.watch(value=>{if(value.items.some(x=>x.id===fund)){clearTimeout(timeout);resolve(value);}},reject);});assert.equal(snapshot.spaces.length,1);assert.equal(snapshot.items.find(x=>x.id===fund).balance,300);observer.close();});

test('task rotation wraps, advances valid dates, and one-off tasks finish',()=>{const task={assignees:['a','b'],turn:1,repeatDays:7,dueDate:'2026-12-28'};assert.deepEqual(nextTaskTurn(task,'2026-12-30'),{status:'active',turn:0,dueDate:'2027-01-06'});assert.equal(nextTaskTurn({...task,repeatDays:0},'2026-12-30').status,'done');assert.throws(()=>validUtilityDate('2026-02-30'));});
test('loans track partial returns and goods; borrower cannot self-confirm repayment',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),loan=await owner.add(id,'loan',{title:'Cash loan',loanType:'money',lender:'owner',borrower:'member',amount:10000,dueDate:'2026-11-01'});await assert.rejects(()=>member.returnLoan(loan,10000,'bad'));await owner.returnLoan(loan,3000,'first');await owner.returnLoan(loan,3000,'first');let x=(await getDoc(doc(owner.db,'utilityItems',loan))).data();assert.equal(x.returnedCents,3000);assert.equal(x.returnLog.length,1);assert.equal(x.status,'active');await assert.rejects(()=>owner.returnLoan(loan,7001,'over'));await owner.returnLoan(loan,7000,'second');assert.equal((await getDoc(doc(owner.db,'utilityItems',loan))).data().status,'done');const item=await member.add(id,'loan',{title:'Luggage',loanType:'item',lender:'member',borrower:'owner',dueDate:'2026-12-01',quantity:'1'});await member.returnLoan(item,0,'returned');assert.equal((await getDoc(doc(owner.db,'utilityItems',item))).data().status,'done');});
test('task completion keeps history, rotates and is idempotent; unrelated members cannot complete',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),task=await owner.add(id,'task',{title:'Shopping duty',assignees:['owner','member'],repeatDays:7,dueDate:'2026-10-10'});await assert.rejects(()=>member.completeTask(task,'2026-10-10','bad'));await owner.completeTask(task,'2026-10-10','first');await owner.completeTask(task,'2026-10-10','first');let x=(await getDoc(doc(owner.db,'utilityItems',task))).data();assert.equal(x.turn,1);assert.equal(x.completionLog.length,1);assert.equal(x.dueDate,'2026-10-17');await member.completeTask(task,'2026-10-17','second');x=(await getDoc(doc(owner.db,'utilityItems',task))).data();assert.equal(x.turn,0);assert.equal(x.dueDate,'2026-10-24');assert.equal(x.completionLog.length,2);const once=await owner.add(id,'task',{title:'One task',assignees:['member'],repeatDays:0,dueDate:'2026-10-10'});await member.completeTask(once,'2026-10-10','done');assert.equal((await getDoc(doc(owner.db,'utilityItems',once))).data().status,'done');});
test('board notes support author edits, owner pins and only self read acknowledgements',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),post=await member.add(id,'board',{title:'Gathering',body:'Sunday lunch',eventDate:'2026-11-01',pinned:false});await owner.boardAction(post,'pin');await owner.boardAction(post,'read');await owner.boardAction(post,'read');let x=(await getDoc(doc(owner.db,'utilityItems',post))).data();assert.equal(x.pinned,true);assert.equal(x.readBy.length,2);await assert.rejects(()=>owner.boardAction(post,'edit',{title:'No',body:'No'}));await member.boardAction(post,'edit',{title:'Lunch',body:'At home',eventDate:'2026-11-02'});x=(await getDoc(doc(owner.db,'utilityItems',post))).data();assert.equal(x.title,'Lunch');assert.equal(x.body,'At home');await assert.rejects(()=>updateDoc(doc(member.db,'utilityItems',post),{readBy:['member']}));await member.change(post,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',post))).data().status,'done');});

test('shopping bulk parses item quantities and validates limits',()=>{assert.deepEqual(shoppingBulk('Rice | 5kg\nMilk | 2 boxes\nEggs\nBread | 1'),[{title:'Rice',quantity:'5kg'},{title:'Milk',quantity:'2 boxes'},{title:'Eggs',quantity:'1'},{title:'Bread',quantity:'1'}]);assert.throws(()=>shoppingBulk(''));assert.throws(()=>shoppingBulk(Array(51).fill('Item').join('\n')));});
test('shopping events bulk assign, retry safely, isolate events and preserve legacy items',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),event=await owner.add(id,'shoppingEvent',{title:'BBQ',eventDate:'2026-11-01'});await owner.addShoppingItems(event,'Rice | 5kg\nMilk\nEggs\nBread','member','four');await owner.addShoppingItems(event,'Rice | 5kg\nMilk\nEggs\nBread','member','four');let rows=(await getDocs(query(collection(owner.db,'utilityItems'),where('spaceId','==',id)))).docs.map(d=>({...d.data(),id:d.id}));assert.equal(rows.filter(x=>x.eventId===event).length,4);assert.ok(rows.filter(x=>x.eventId===event).every(x=>x.assignee==='member'));await assert.rejects(()=>member.addShoppingItems(event,'Extra','member','not-creator'));await assert.rejects(()=>owner.assignShopping('shop_four_0','outsider'));await assert.rejects(()=>owner.change(event,'toggle'));await member.change('shop_four_0','toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems','shop_four_0'))).data().completedBy,'member');await owner.assignShopping('shop_four_1','owner');await assert.rejects(()=>member.change('shop_four_1','toggle'));for(const n of [1,2,3])await owner.change('shop_four_'+n,'toggle');await owner.change(event,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',event))).data().status,'done');await assert.rejects(()=>owner.addShoppingItems(event,'Late','owner','late'));await owner.change(event,'toggle');await member.change('shop_four_0','toggle');const legacy=await owner.add(id,'shopping',{title:'Old',quantity:'1'});await member.change(legacy,'toggle');assert.equal((await getDoc(doc(owner.db,'utilityItems',legacy))).data().status,'done');});

test('shopping event accepts a full 50 item batch atomically',{skip:!enabled},async()=>{const {owner,id}=await setup(),event=await owner.add(id,'shoppingEvent',{title:'Big event'});await owner.addShoppingItems(event,Array.from({length:50},(_,i)=>'Item '+i).join('\n'),'member','fifty');const rows=await getDocs(query(collection(owner.db,'utilityItems'),where('spaceId','==',id)));assert.equal(rows.docs.filter(x=>x.data().eventId===event).length,50);});

test('board attachments validate files and reject executable data URLs or oversized data',()=>{assert.equal(validateAttachment({kind:'file',name:'test.pdf',dataUrl:'data:application/octet-stream;base64,JVBERg=='}).kind,'file');assert.throws(()=>validateAttachment({kind:'file',name:'test.html',dataUrl:'data:text/html;base64,SGk='}));assert.throws(()=>validateAttachment({kind:'file',name:'big.pdf',dataUrl:'data:application/octet-stream;base64,'+'A'.repeat(600001)}));assert.equal(validateAttachment(null),null);});
test('board images and files are shared only with space members; replace and remove atomically',{skip:!enabled},async()=>{const {owner,member,id}=await setup(),attachment={kind:'file',name:'event.pdf',dataUrl:'data:application/octet-stream;base64,JVBERg=='},post=await owner.add(id,'board',{title:'Plan',body:'Attached',attachment});assert.equal((await member.getAttachment(post)).name,'event.pdf');await assert.rejects(()=>repo('stranger').getAttachment(post));await assert.rejects(()=>member.boardAction(post,'edit',{title:'Bad',attachment:null}));const image={kind:'image',name:'photo.png',dataUrl:'data:image/png;base64,aGVsbG8='};await owner.boardAction(post,'edit',{title:'Plan',body:'Updated',attachment:image});assert.equal((await member.getAttachment(post)).kind,'image');await owner.boardAction(post,'edit',{title:'Plan',body:'Keep'});assert.equal((await member.getAttachment(post)).kind,'image');await owner.boardAction(post,'edit',{title:'Plan',body:'Removed',attachment:null});assert.equal((await getDoc(doc(owner.db,'utilityItems',post))).data().hasAttachment,false);assert.equal(await member.getAttachment(post),null);});
