import {providerNotifications,bindNotificationSettings} from './notifications.js';
import {premiumViews} from './premium-views.js';
import {readProof} from './proof.mjs';
import {bindTheme} from './theme.js';
import {serviceIcon} from './icons.mjs';
import './install.js';
import {ownerDashboard} from './owner-dashboard.mjs';
import {simpleViews} from './simple-views.js';
import {setupFeatures} from './features.js';
import './style.css';
import {GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut} from 'firebase/auth';
import {auth,db,useEmulators} from './firebase.js';
import {Repository} from './repository.mjs';
import {settlement,summary,moneyInput,cents} from './model.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),rm=n=>'RM '+(n/100).toFixed(2);
let state={subscriptions:[],charges:[],payments:[],members:[],activity:[]},user=null,profile=null,repo=null,view='subscriptions',primaryView='subscriptions',filter='all',selected='all',busy=false,authGeneration=0,webMcpLifecycle=null,landingChosen=false;
const viewNames={dashboard:'Dashboard kutipan',subscriptions:'Subscription',payments:'Bayaran saya',profile:'Profil',log:'Sejarah bayaran',bills:'Bil & pelan hutang'};
const subs=()=>state.subscriptions.filter(s=>selected==='all'||s.id===selected),owner=s=>s.createdBy===user?.uid,owned=()=>subs().filter(owner),member=id=>state.members.find(m=>m.id===id),memberName=id=>member(id)?.name||'Ahli',sub=id=>state.subscriptions.find(s=>s.id===id),chargeList=()=>state.charges.filter(c=>!c.self&&(selected==='all'||c.subscription===selected)&&((view==='payments'||(view==='log'&&primaryView==='payments'))?c.member===user?.uid:true)),canPay=c=>c.member===user?.uid||c.owner===user?.uid,s=sum=>sum.reduce((n,v)=>n+v,0);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),dateLabel=d=>d?new Date(d+'T12:00:00Z').toLocaleDateString('ms-MY',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kuala_Lumpur'}):'Belum ditetapkan';
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4500);}
function friendly(e){const code=e?.code||'';if(code==='auth/unauthorized-domain')return 'Domain ini belum dibenarkan untuk login Google. Hubungi owner untuk semak tetapan login.';if(code==='auth/popup-blocked')return 'Popup login disekat. Benarkan popup untuk KongsiPay dan cuba lagi.';if(code==='auth/popup-closed-by-user'||code==='auth/cancelled-popup-request')return 'Login belum selesai. Tekan Google untuk cuba semula.';if(code==='permission-denied')return 'Akses data ditolak. Semak akaun dan keahlian subscription anda.';if(code==='auth/network-request-failed'||code==='unavailable')return 'Sambungan terganggu. Semak internet dan cuba lagi.';return e?.message||'Tindakan gagal. Cuba semula.';}
function authPage(message='',loading=false){$('#app-shell').hidden=true;$('#auth-screen').hidden=false;$('#auth-content').innerHTML=loading?`<h1>Sedang menyambung…</h1><p class="lead" role="status">${esc(message||'Memuatkan subscription anda.')}</p>`:`<span class="eyebrow">SUBSCRIPTION BERSAMA</span><h1>Duit kongsi,<br>semua jelas.</h1><p class="lead">Log masuk atau daftar menggunakan Google. Jika anda pengguna PayTrack, pilih akaun yang sama untuk melihat rekod sedia ada.</p><button class="google-btn" id="google-login"><span class="google-g" aria-hidden="true">G</span> Teruskan dengan Google</button>${message?`<p class="auth-error" role="alert">${esc(message)}</p>`:''}<p class="auth-note">Akaun baharu didaftarkan semasa login pertama.</p>`;if($('#google-login'))$('#google-login').onclick=async()=>{const button=$('#google-login');button.disabled=true;button.textContent='Membuka Google…';const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{await signInWithPopup(auth,provider);}catch(e){authPage(friendly(e));}};}
function syncError(e){$('#sync-status').textContent='Sambungan bermasalah';toast(friendly(e));if($('#app-shell').hidden){authPage(friendly(e));$('#auth-content').insertAdjacentHTML('beforeend','<button class="secondary" id="retry-data">Cuba sambung semula</button><button class="text-btn" id="retry-logout">Tukar akaun</button>');$('#retry-data').onclick=()=>boot(user);$('#retry-logout').onclick=()=>signOut(auth);}}
function updateIdentity(){const name=profile?.name||user.displayName||user.email?.split('@')[0]||'Ahli';$('#profile-name').textContent=name;$('#profile-avatar').textContent=name[0].toUpperCase();$('#header-avatar').textContent=name[0].toUpperCase();$('#profile-role').textContent=state.subscriptions.some(owner)?'Owner & ahli':'Ahli KongsiPay';$('#month').textContent=new Date().toLocaleDateString('ms-MY',{month:'long',year:'numeric',timeZone:'Asia/Kuala_Lumpur'});}
function selectOptions(){const opts='<option value="all">Semua subscription</option>'+state.subscriptions.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');for(const id of ['#group','#group-mobile']){$(id).innerHTML=opts;$(id).value=selected;}}
function heading(title,text,action=''){return `<div class="title-row"><div><h1>${title}</h1><p class="lead">${text}</p></div>${action}</div>`;}
function status(c){const x=settlement(c,state.payments);if(!x.balance)return `<span class="badge">${x.forgiven?'Dimaafkan':'Dah bayar'}</span>`;if(x.pending)return '<span class="badge wait">Dalam semakan</span>';if(x.cleared)return '<span class="badge wait">Bayar sebahagian</span>';return c.due<today()?'<span class="badge debt">Tertunggak</span>':'<span class="badge neutral">Belum bayar</span>';}
function icon(sub){return serviceIcon(sub);}
function chargeTable(cs){return `<div class="table-wrap"><table><thead><tr><th>Ahli / penerima</th><th>Subscription</th><th>Tarikh akhir</th><th>Baki</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>${cs.length?cs.map(c=>{const x=settlement(c,state.payments);return `<tr data-charge="${esc(c.id)}"><td>${esc(memberName(c.member))}${c.member===user.uid?' <span class="you-label">Anda</span>':''}<small>${c.member===c.payee?'Bahagian sendiri':'Kepada '+esc(memberName(c.payee))}</small></td><td>${esc(sub(c.subscription)?.name)}<small>${esc(c.period)}</small></td><td>${dateLabel(c.due)}</td><td>${rm(x.balance)}<small>Daripada ${rm(c.amount)}</small></td><td>${status(c)}</td><td><button class="text-btn" data-timeline="${esc(c.id)}">Timeline</button>${canPay(c)&&x.available>0?`<button class="table-btn" data-pay="${esc(c.id)}">Bayar</button>`:'<span class="muted">—</span>'}</td></tr>`;}).join(''):'<tr><td colspan="6" class="empty">Tiada caj dalam paparan ini.</td></tr>'}</tbody></table></div>`;}
function render(){if(!user)return;if(selected!=='all'&&!sub(selected))selected='all';const isOwner=state.subscriptions.some(owner);document.querySelector('[data-view=dashboard]').hidden=!isOwner;document.querySelector('nav').classList.toggle('has-owner',isOwner);if(view==='dashboard'&&!isOwner)view=primaryView='subscriptions';selectOptions();updateIdentity();$('#crumb').textContent=view==='bills'?sub(selected)?.name||'Subscription':viewNames[view];$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===primaryView));$('#content').innerHTML=({dashboard:dashboard.render,subscriptions:simple.subscriptions,payments:simple.payments,profile:simple.profile,log:()=>'<button class="text-btn back" data-back>‹ Kembali</button>'+features.log(),bills:simple.detail}[view])();bind();features.decorate();simple.bind();dashboard.bind();premium.bind();bindTheme();bindNotificationSettings();notices.render();}
function navigate(v){if(!viewNames[v])throw Error('Paparan tidak sah.');if(['dashboard','subscriptions','payments','profile'].includes(v)){primaryView=v;selected='all';filter='all';features.reset();}view=v;render();window.scrollTo(0,0);}
function modal(title,html,submit,label='Simpan'){$('#modal-title').textContent=title;$('#fields').innerHTML=html;$('#error').textContent='';$('#submit').textContent=label;$('#submit').disabled=false;$('#form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#submit').disabled=true;$('#submit').textContent='Menyimpan…';$('#error').textContent='';$('#cancel').disabled=true;$('#close').disabled=true;try{await submit(new FormData(e.target));$('#modal').close();}catch(err){$('#error').textContent=friendly(err);}finally{busy=false;$('#submit').disabled=false;$('#submit').textContent=label;$('#cancel').disabled=false;$('#close').disabled=false;}};$('#modal').showModal();}
function pay(id){const c=state.charges.find(c=>c.id===id);if(!c||!canPay(c))return;const x=settlement(c,state.payments),receiver=member(c.payee),requestId=crypto.randomUUID();let proof=null,proofLoading=false;const qr=receiver?.qrUrl;const safeQr=qr&&(/^(data:image\/(png|jpeg|webp);base64,)/.test(qr)||/^https:\/\//.test(qr));modal('Rekod bayaran',`<p class="help">${esc(memberName(c.member))} · ${esc(sub(c.subscription)?.name)}<br>${esc(c.period)} · ${c.member===c.payee?'Bahagian sendiri':'Bayar kepada '+esc(memberName(c.payee))}</p>${safeQr?`<div class="qr-wrap"><img class="payment-qr" src="${esc(qr)}" alt="QR bayaran ${esc(receiver.name)}" referrerpolicy="no-referrer"></div>`:''}<label for="amount">Jumlah (RM) — maks. ${rm(x.available)}</label><input id="amount" name="amount" type="number" min="0.01" step="0.01" max="${x.available/100}" value="${(x.available/100).toFixed(2)}" required><label for="method">Kaedah bayaran</label><select id="method" name="method"><option>Bank transfer</option><option>DuitNow</option><option>E-wallet</option><option>Cash</option></select><label for="reference">Reference / nota</label><input id="reference" name="reference" maxlength="160" placeholder="Contoh: BAYAR-OKT-001"><label for="payment-proof">Bukti transfer (pilihan)</label><input id="payment-proof" type="file" accept="image/png,image/jpeg,image/webp"><p class="help">Imej sehingga 8MB; app mengecilkan imej untuk simpanan. Bukti hanya boleh dibuka oleh anda dan owner.</p><div id="proof-preview"></div><p class="help">Buat bayaran melalui kaedah yang dipersetujui dahulu. Butang ini merekodkan bayaran untuk semakan owner; ia tidak memindahkan wang.</p>`,async f=>{if(proofLoading)throw Error('Tunggu bukti selesai diproses.');await repo.recordPayment({...c,amount:moneyInput(f.get('amount')),method:f.get('method'),reference:f.get('reference'),requestId,proof});toast('Bayaran dihantar untuk semakan owner.');const entry={...c,amount:moneyInput(f.get('amount'))};setTimeout(()=>features.notification([entry]),50);},'Hantar untuk semakan');$('#payment-proof').onchange=async()=>{proof=null;proofLoading=true;$('#submit').disabled=true;try{proof=await readProof($('#payment-proof').files[0]);$('#proof-preview').innerHTML=proof?`<img class="proof-thumb" src="${esc(proof.dataUrl)}" alt="Bukti dipilih">`:'';$('#error').textContent='';}catch(e){$('#payment-proof').value='';$('#proof-preview').innerHTML='';$('#error').textContent=e.message;}finally{proofLoading=false;$('#submit').disabled=false;}};}
function bind(){$$('[data-back]').forEach(b=>b.onclick=()=>navigate(selected==='all'?primaryView:'bills'));$$('[data-profile-edit]').forEach(b=>b.onclick=()=>features.profile());$$('[data-signout]').forEach(b=>b.onclick=()=>signOut(auth).catch(e=>toast(friendly(e))));$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$$('[data-add-sub]').forEach(b=>b.onclick=addSub);$$('[data-open-sub]').forEach(b=>b.onclick=()=>{selected=b.dataset.openSub;filter='all';primaryView='subscriptions';features.reset();navigate('bills');});$$('[data-pay]').forEach(b=>b.onclick=()=>pay(b.dataset.pay));$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});$$('[data-invite]').forEach(b=>b.onclick=()=>invite(b.dataset.invite));$$('[data-cycle]').forEach(b=>b.onclick=()=>cycle(b.dataset.cycle));$$('[data-approve]').forEach(b=>b.onclick=()=>modal('Sahkan bayaran','<p class="help">Pastikan duit telah diterima. Baki ahli dikurangkan apabila bayaran ini disahkan.</p>',async()=>{await repo.reviewPayment(b.dataset.approve,true);toast('Bayaran disahkan. Baki dikemas kini.');},'Sahkan'));$$('[data-reject]').forEach(b=>b.onclick=()=>modal('Tolak bayaran','<label for="reason">Sebab penolakan</label><input id="reason" name="reason" required maxlength="160">',async f=>{await repo.reviewPayment(b.dataset.reject,false,String(f.get('reason')));toast('Bayaran ditolak. Baki kekal.');}));if($('#invite-member'))$('#invite-member').onclick=()=>invite(selected);if($('#export'))$('#export').onclick=exportCSV;}
function exportCSV(){const rows=[['Ahli','Penerima','Subscription','Kitaran','Jumlah RM','Disahkan RM','Baki RM'],...chargeList().map(c=>{const x=settlement(c,state.payments);return [memberName(c.member),memberName(c.payee),sub(c.subscription)?.name,c.period,(c.amount/100).toFixed(2),(x.received/100).toFixed(2),(x.balance/100).toFixed(2)];})];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='kongsipay-penyata.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function boot(u){const generation=++authGeneration;repo?.close();webMcpLifecycle?.abort();webMcpLifecycle=null;repo=null;state={subscriptions:[],charges:[],payments:[],members:[],activity:[]};user=u;profile=null;view='subscriptions';primaryView='subscriptions';selected='all';filter='all';landingChosen=false;features.reset();dashboard.reset();notices.reset();$('#modal').close();if(!u){authPage();return;}authPage('Memuatkan subscription dan rekod bayaran anda.',true);const current=new Repository(db,u);repo=current;try{profile=await current.profile();if(generation!==authGeneration)return;try{await current.acceptInvites();}catch(e){toast('Jemputan belum dapat disemak. '+friendly(e));}if(generation!==authGeneration)return;current.watch(data=>{if(generation!==authGeneration)return;state=data;if(!landingChosen){landingChosen=true;if(state.subscriptions.some(owner))view=primaryView='dashboard';}$('#auth-screen').hidden=true;$('#app-shell').hidden=false;$('#sync-status').textContent='Data diselaraskan';render();registerWebMcp();},syncError);}catch(e){if(generation===authGeneration)syncError(e);}}
function registerWebMcp(){if(webMcpLifecycle||!document.modelContext?.registerTool)return;webMcpLifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_payment_summary',description:'Read payment totals for the signed-in member and selected accessible subscriptions. Does not transfer money.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No input fields accepted.');if(!user)throw Error('Sign in required.');const totals=summary(state,chargeList());return {currency:'MYR',subscriptionCount:subs().length,outstandingCents:totals.outstanding,pendingCents:totals.pending,receivedCents:totals.received};}},{signal:webMcpLifecycle.signal})).catch(()=>{});}catch{}}
const features=setupFeatures({get state(){return state},get repo(){return repo},get user(){return user},get profile(){return profile},get selected(){return selected},get view(){return view},get onlyMine(){return primaryView==='payments'},esc,rm,modal,toast,today,dateLabel,heading,chargeTable,chargeList,canPay,proofButton:p=>premium.proofButton(p),render,navigate});
const notices=providerNotifications({get state(){return state},get user(){return user},esc,rm,modal,toast,bind:()=>premium.bind()});
const premium=premiumViews({get state(){return state},get repo(){return repo},get user(){return user},get profile(){return profile},esc,rm,dateLabel,modal,toast,today,chargeList,canPay});
const simple=simpleViews({get state(){return state},get user(){return user},get profile(){return profile},get selected(){return selected},get filter(){return filter},esc,rm,heading,chargeTable,dateLabel,icon,premium,render});
const dashboard=ownerDashboard({get state(){return state},get user(){return user},esc,rm,heading,chargeTable,today,reminders:o=>premium.reminders(o),exportPDF:(cs,title)=>premium.exportPDF(cs,title),proofButton:p=>premium.proofButton(p),render});
const addSub=()=>features.addSub(),invite=id=>features.invite(id),cycle=id=>features.cycle(id);
$$('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.view));for(const id of ['#group','#group-mobile'])$(id).onchange=e=>{selected=e.target.value;render();};$('#close').onclick=$('#cancel').onclick=()=>{if(!busy)$('#modal').close();};$('#modal').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('#logout').onclick=$('#mobile-logout').onclick=()=>signOut(auth).catch(e=>toast(friendly(e)));
onAuthStateChanged(auth,boot,e=>authPage(friendly(e)));
document.addEventListener('click',async e=>{const button=e.target.closest('[data-invites]');if(!button||!repo)return;button.disabled=true;try{const count=await repo.acceptInvites();toast(count?'Jemputan diterima. Subscription akan muncul sebentar lagi.':'Tiada jemputan baharu untuk akaun ini.');}catch(err){toast(friendly(err));}finally{button.disabled=false;}});


if(import.meta.env.DEV&&useEmulators)import('./emulator-login.js').then(({installEmulatorLogin})=>installEmulatorLogin(auth));
