import {providerAmount} from './premium.mjs';
export function providerNotifications(ctx){
  let activeUid=null,known=new Set();
  const key=()=>`kongsipay-notices-${ctx.user.uid}`;
  const seen=()=>{try{return new Set(JSON.parse(localStorage.getItem(key())||'[]'));}catch{return new Set();}};
  const events=()=>ctx.state.subscriptions.flatMap(s=>s.cycles.filter(c=>c.providerPaidAt&&s.createdBy!==ctx.user.uid).map(c=>({key:c.id+'-'+c.providerPaidAt,sub:s,cycle:c}))).sort((a,b)=>b.cycle.providerPaidAt-a.cycle.providerPaidAt);
  function render(){const items=events(),read=seen(),unread=items.filter(e=>!read.has(e.key));let button=document.querySelector('#provider-notices');if(!button){button=document.createElement('button');button.id='provider-notices';button.className='secondary notices-button';document.querySelector('.header-right').prepend(button);}button.textContent='Notis'+(unread.length?' · '+unread.length:'');button.setAttribute('aria-label',`${unread.length} notis belum dibaca`);button.onclick=()=>{ctx.modal('Notis subscription',`<p class="help">Bukti pembayaran provider daripada owner subscription anda.</p>${items.map(e=>`<div class="notice-item"><strong>${ctx.esc(e.sub.name)} · ${ctx.esc(e.cycle.label)}</strong><p class="help">Owner dah bayar provider ${providerAmount(e.cycle)?ctx.rm(providerAmount(e.cycle)):"(jumlah belum diisi; rujuk bukti)"} pada ${new Date(e.cycle.providerPaidAt).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur'})}.</p>${e.cycle.hasProviderProof?`<button type="button" class="secondary" data-provider-proof="${ctx.esc(e.cycle.id)}">Lihat bukti provider</button>`:'<small>Bukti belum dilampirkan.</small>'}${!read.has(e.key)?'<span class="badge">Baharu</span>':''}</div>`).join('')||'<p class="empty">Belum ada notis pembayaran provider.</p>'}`,async()=>{try{localStorage.setItem(key(),JSON.stringify(items.map(e=>e.key).slice(0,300)));}catch{}render();},'Tanda dibaca');ctx.bind();};
    if(activeUid===ctx.user.uid){for(const e of items.filter(e=>!known.has(e.key))){ctx.toast(`${e.sub.name}: owner dah bayar provider${e.cycle.hasProviderProof?' dan upload bukti':''}.`);if(globalThis.Notification?.permission==='granted'&&localStorage.getItem('kongsipay-browser-notices')==='on'){try{new Notification('KongsiPay — bil provider dibayar',{body:`${e.sub.name} · ${e.cycle.label}. Buka KongsiPay untuk semak bukti.`,icon:`${import.meta.env.BASE_URL}icons/icon-192.png`,tag:e.key});}catch{}}}}activeUid=ctx.user.uid;known=new Set(items.map(e=>e.key));}
  function reset(){activeUid=null;known=new Set();}
  return {render,reset};
}
export function notificationSettings(){return `<div class="notification-setting"><h3>Notifikasi browser</h3><p class="help">Terima notis bila owner membayar provider ketika KongsiPay sedang dibuka. Notis dalam app sentiasa tersedia.</p><button type="button" class="secondary" id="enable-browser-notices">${globalThis.Notification?.permission==='granted'?'Tetapan notifikasi':'Aktifkan notifikasi'}</button><p class="help" id="notification-permission-status"></p></div>`;}
export function bindNotificationSettings(){const b=document.querySelector('#enable-browser-notices');if(!b)return;const status=document.querySelector('#notification-permission-status');const update=()=>{const on=localStorage.getItem('kongsipay-browser-notices')==='on';status.textContent=globalThis.Notification?.permission==='granted'?(on?'Notifikasi browser aktif.':'Notifikasi browser dimatikan.'):'Notifikasi bergantung pada sokongan dan izin browser.';b.textContent=globalThis.Notification?.permission==='granted'?(on?'Matikan notifikasi':'Aktifkan notifikasi'):'Aktifkan notifikasi';};update();b.onclick=async()=>{if(!globalThis.Notification){status.textContent='Browser ini tidak menyokong notifikasi. Gunakan notis dalam app.';return;}if(Notification.permission==='granted'){localStorage.setItem('kongsipay-browser-notices',localStorage.getItem('kongsipay-browser-notices')==='on'?'off':'on');update();return;}const permission=await Notification.requestPermission();if(permission==='granted')localStorage.setItem('kongsipay-browser-notices','on');update();if(permission==='denied')status.textContent='Izin ditolak. Anda masih menerima notis dalam app.';};}
