import {split} from './model.mjs';
export function expenseShares(amount,members){if(!Number.isSafeInteger(amount)||amount<1||!members.length||new Set(members).size!==members.length)throw Error('Pilih ahli dan jumlah yang sah.');return Object.fromEntries(split(amount,members).map(x=>[x.member,x.amount]));}
export function expenseBalance(item){return Object.entries(item.shares).filter(([uid])=>uid!==item.payer&&!item.settled.includes(uid)).reduce((n,[,amount])=>n+amount,0);}
export function fundBalance(items,id){return items.filter(x=>x.kind==='entry'&&x.fundId===id).reduce((n,x)=>n+(x.entryType==='contribution'?x.amount:-x.amount),0);}
export function utilityAttention(items){return {expense:items.filter(x=>x.kind==='expense'&&x.status==='active'&&expenseBalance(x)>0).length,fund:items.filter(x=>x.kind==='fund'&&x.status==='active').length,shopping:items.filter(x=>x.kind==='shopping'&&x.status==='active').length,loan:items.filter(x=>x.kind==='loan'&&x.status==='active').length,task:items.filter(x=>x.kind==='task'&&x.status==='active').length,board:items.filter(x=>x.kind==='board'&&x.status==='active').length,calendar:items.filter(x=>x.kind==='calendarEvent'&&x.status==='active').length};}

export function validUtilityDate(value,optional=false){if(optional&&!value)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value)))throw Error('Pilih tarikh yang sah.');const d=new Date(value+'T12:00:00Z');if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==value)throw Error('Pilih tarikh yang sah.');return value;}
export function nextTaskTurn(task,today){validUtilityDate(today);if(!task.repeatDays)return {status:'done',turn:task.turn,dueDate:task.dueDate};const d=new Date((task.dueDate>today?task.dueDate:today)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+task.repeatDays);return {status:'active',turn:(task.turn+1)%task.assignees.length,dueDate:d.toISOString().slice(0,10)};}

export function shoppingBulk(text){const rows=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!rows.length||rows.length>50)throw Error('Masukkan 1–50 item, satu item setiap baris.');return rows.map(row=>{const [title,...quantity]=row.split('|').map(x=>x.trim());if(!title||title.length>100||quantity.join(' | ').length>100)throw Error('Nama item dan kuantiti maksimum 100 aksara.');return {title,quantity:quantity.join(' | ')||'1'};});}

export function utilityInviteCandidates(members,space){const seen=new Set((space.pendingEmails||[]).map(e=>e.toLowerCase()));return members.filter(m=>{const email=String(m.email||'').trim().toLowerCase();if(space.memberUids.includes(m.id)||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||seen.has(email))return false;seen.add(email);return true;}).map(m=>({...m,email:m.email.trim().toLowerCase()})).sort((a,b)=>(a.name||'').localeCompare(b.name||''));}
