import {t} from './i18n.js';
import {moneyInput} from './model.mjs';
import {UtilityRepository} from './utility-repository.mjs';
import {expenseBalance,fundBalance,utilityAttention} from './utility-model.mjs';
export function utilityViews(ctx){
 const {esc,rm,modal,toast}=ctx;let repo=null,data={spaces:[],items:[]},spaceId='',page='home',history=false,hidden=[];
 const uid=()=>ctx.user.uid,space=()=>data.spaces.find(x=>x.id===spaceId),items=()=>data.items.filter(x=>x.spaceId===spaceId),name=id=>space()?.profiles[id]?.name||t('Ahli'),own=()=>space()?.createdBy===uid();
 const labels={expense:'Belanja bersama',fund:'Tabung',shopping:'Shopping list'},icons={expense:'💸',fund:'🎯',shopping:'🛒'};
 function loadHidden(){try{hidden=JSON.parse(localStorage.getItem('utility-hidden-'+uid()+'-'+spaceId)||'[]');if(!Array.isArray(hidden))hidden=[];}catch{hidden=[];}}
 function start(db,user){stop();repo=new UtilityRepository(db,user);repo.watch(value=>{data=value;if(!data.spaces.some(x=>x.id===spaceId)){spaceId=data.spaces[0]?.id||'';loadHidden();}if(ctx.visible())ctx.render();},e=>toast(e.message));}
 function stop(){repo?.close();repo=null;data={spaces:[],items:[]};spaceId='';page='home';history=false;hidden=[];}
 function render(){if(!space())return ctx.heading('Utility',t('Ruang bersama untuk belanja, tabung dan barang harian.'))+`<div class="panel empty"><h2>${t('Cipta ruang Utility')}</h2><p>${t('Jemput ahli menggunakan email Google. Keahlian ruang ini berasingan daripada subscription.')}</p><button class="primary" data-u-create>${t('Cipta ruang')}</button><button class="secondary" data-u-accept>${t('Semak jemputan')}</button></div>`;
 const s=space(),attention=utilityAttention(items());let html=ctx.heading('Utility',esc(s.name),`<button class="secondary" data-u-create>${t('Ruang baharu')}</button>`)+`<div class="utility-toolbar"><label>${t('Ruang')}<select id="utility-space">${data.spaces.map(x=>`<option value="${esc(x.id)}" ${x.id===spaceId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><button class="text-btn" data-u-accept>${t('Semak jemputan')}</button>${own()?`<button class="secondary" data-u-invite>${t('Jemput ahli')}</button>`:''}<button class="text-btn" data-u-settings>${t('Paparan Utility')}</button></div><details class="secondary-section"><summary>${t('Ahli ruang')} · ${s.memberUids.length}</summary><p>${s.memberUids.map(id=>esc(name(id))).join(' · ')}</p>${own()&&s.pendingEmails.length?`<p class="help">${t('Menunggu login')}: ${s.pendingEmails.map(esc).join(', ')}</p>`:''}</details>`;
 if(page==='home')return html+`<div class="utility-grid">${Object.keys(labels).filter(k=>!hidden.includes(k)).map(k=>`<button class="panel utility-tile" data-u-page="${k}"><span>${icons[k]}</span><h2>${t(labels[k])}</h2><p>${attention[k]} ${t(k==='expense'?'belanja belum selesai':k==='fund'?'tabung aktif':'barang belum dibeli')}</p></button>`).join('')}</div><div class="panel"><h2>${t('Perlu perhatian')}</h2>${items().filter(x=>x.status==='active'&&x.kind!=='entry'&&!hidden.includes(x.kind)).slice().sort((a,b)=>b.createdAt-a.createdAt).slice(0,6).map(x=>`<button class="utility-attention" data-u-page="${x.kind}"><span>${icons[x.kind]} ${esc(x.title)}</span><strong>${x.kind==='expense'?rm(expenseBalance(x)):x.kind==='fund'?rm(fundBalance(items(),x.id))+' / '+rm(x.target):esc(x.quantity)}</strong></button>`).join('')||`<p class="help">${t('Tiada perkara aktif. Tambah rekod untuk mula.')}</p>`}</div>`;
 const list=items().filter(x=>x.kind===page&&x.status===(history?'done':'active')).sort((a,b)=>b.createdAt-a.createdAt);
 html+=`<button class="text-btn" data-u-page="home">‹ Utility</button><div class="section-title"><h2>${t(labels[page])}</h2><button class="primary" data-u-add>${t('Tambah')}</button></div><div class="actions"><button class="${history?'secondary':'primary'}" data-u-history="false">${t('Aktif')}</button><button class="${history?'primary':'secondary'}" data-u-history="true">${t('Sejarah')}</button></div>`;
 return html+list.map(x=>{
 if(x.kind==='shopping')return `<article class="panel utility-row"><div><h3>${esc(x.title)}</h3><small>${esc(x.quantity)} · ${esc(name(x.createdBy))}</small></div><button class="${history?'secondary':'primary'}" data-u-toggle="${esc(x.id)}">${t(history?'Belum dibeli':'Dah beli')}</button></article>`;
 if(x.kind==='expense')return `<details class="panel"><summary class="utility-row"><span><strong>${esc(x.title)}</strong><small>${t('Dibayar oleh')} ${esc(name(x.payer))} · ${rm(x.amount)}</small></span><strong>${rm(expenseBalance(x))} ${t('Baki')}</strong></summary>${x.participants.map(id=>`<div class="subrow"><span>${esc(name(id))}</span><strong>${rm(x.shares[id])}</strong>${x.settled.includes(id)?`<span class="badge">${t('Dah selesai')}</span>`:x.payer===uid()?`<button class="secondary" data-u-settle="${esc(x.id)}" data-u-member="${esc(id)}">${t('Sahkan diterima')}</button>`:`<span class="badge neutral">${t('Belum bayar')}</span>`}</div>`).join('')}<p class="help">${t('Pembayar mengesahkan selepas duit diterima. App tidak memindahkan wang.')}</p>${x.createdBy===uid()&&!expenseBalance(x)?`<button class="text-btn" data-u-toggle="${esc(x.id)}">${t(history?'Aktifkan semula':'Arkibkan')}</button>`:''}</details>`;
 const balance=fundBalance(items(),x.id),ledger=items().filter(e=>e.kind==='entry'&&e.fundId===x.id).sort((a,b)=>b.createdAt-a.createdAt);
 return `<details class="panel"><summary class="utility-row"><span><strong>${esc(x.title)}</strong><small>${t('Target')}: ${rm(x.target)}</small></span><strong>${rm(balance)}</strong></summary><progress class="utility-progress" max="${x.target}" value="${Math.max(0,balance)}"></progress><p>${Math.round(balance/x.target*100)}% · ${t('Baki tabung')}: ${rm(balance)}</p>${!history?`<div class="actions"><button class="primary" data-u-entry="${esc(x.id)}" data-u-type="contribution">${t('Rekod sumbangan')}</button>${x.createdBy===uid()?`<button class="secondary" data-u-entry="${esc(x.id)}" data-u-type="withdrawal">${t('Rekod penggunaan')}</button>`:''}</div>`:''}${ledger.map(e=>`<div class="subrow"><div><strong>${esc(e.title)}</strong><small>${esc(name(e.createdBy))} · ${ctx.dateLabel(new Date(e.createdAt).toISOString().slice(0,10))}</small></div><span>${e.entryType==='withdrawal'?'−':'+'}${rm(e.amount)}</span></div>`).join('')||`<p class="help">${t('Belum ada transaksi.')}</p>`}${x.createdBy===uid()?`<button class="text-btn" data-u-toggle="${esc(x.id)}">${t(history?'Aktifkan semula':'Arkibkan')}</button>`:''}</details>`;
 }).join('')+(!list.length?`<div class="panel empty">${t('Tiada rekod dalam pilihan ini.')}</div>`:'');}
 const input=(label,name,type='text',extra='')=>`<label>${t(label)}<input name="${name}" type="${type}" ${extra} required></label>`;
 function add(){const s=space();modal(t(labels[page]),input('Nama','title','text','maxlength="100"')+(page==='shopping'?input('Kuantiti / nota','quantity','text','maxlength="100" value="1"'):page==='fund'?input('Target (RM)','target','number','min="0.01" max="1000000" step="0.01"'):input('Jumlah (RM)','amount','number','min="0.01" max="1000000" step="0.01"')+`<label>${t('Dibayar oleh')}<select name="payer">${s.memberUids.map(id=>`<option value="${esc(id)}" ${id===uid()?'selected':''}>${esc(name(id))}</option>`).join('')}</select></label><fieldset><legend>${t('Ahli yang kongsi')}</legend>${s.memberUids.map(id=>`<label class="check-row"><input type="checkbox" name="participants" value="${esc(id)}" checked>${esc(name(id))}</label>`).join('')}</fieldset><p class="help">${t('Jumlah dibahagi sama rata, tepat hingga sen. Pembayar mesti termasuk dalam pilihan ahli.')}</p>`),async f=>{await repo.add(spaceId,page,{title:f.get('title'),quantity:f.get('quantity'),target:page==='fund'?moneyInput(f.get('target')):undefined,amount:page==='expense'?moneyInput(f.get('amount')):undefined,payer:f.get('payer'),participants:f.getAll('participants')});toast(t('Rekod disimpan.'));});}
 function bind(){const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],bindAll=(selector,fn)=>$$(selector).forEach(b=>b.onclick=()=>fn(b));if($('#utility-space'))$('#utility-space').onchange=e=>{spaceId=e.target.value;page='home';history=false;loadHidden();ctx.render();};bindAll('[data-u-page]',b=>{page=b.dataset.uPage;history=false;ctx.render();});bindAll('[data-u-history]',b=>{history=b.dataset.uHistory==='true';ctx.render();});bindAll('[data-u-create]',()=>modal(t('Cipta ruang Utility'),input('Nama ruang','name','text','maxlength="100"'),async f=>{spaceId=await repo.createSpace(f.get('name'));page='home';loadHidden();toast(t('Ruang dicipta.'));}));bindAll('[data-u-accept]',async()=>{try{const count=await repo.acceptInvites();toast(t(count?'Jemputan diterima.':'Tiada jemputan baharu.'));}catch(e){toast(e.message);}});bindAll('[data-u-invite]',()=>modal(t('Jemput ahli'),input('Email Google','email','email','maxlength="254"'),async f=>{await repo.invite(spaceId,f.get('email'));toast(t('Jemputan disimpan. Minta ahli tekan Semak jemputan di Utility.'));}));bindAll('[data-u-add]',add);bindAll('[data-u-toggle]',b=>modal(t('Ubah status'),`<p>${t('Kemaskini status rekod ini?')}</p>`,async()=>{await repo.change(b.dataset.uToggle,'toggle');}));bindAll('[data-u-settle]',b=>modal(t('Sahkan diterima'),`<p>${t('Pastikan wang telah diterima.')} ${esc(name(b.dataset.uMember))}</p>`,async()=>repo.change(b.dataset.uSettle,'settle',b.dataset.uMember)));bindAll('[data-u-entry]',b=>{const requestId=crypto.randomUUID();modal(t(b.dataset.uType==='contribution'?'Rekod sumbangan':'Rekod penggunaan'),input('Jumlah (RM)','amount','number','min="0.01" max="1000000" step="0.01"')+input('Nota transaksi','title','text','maxlength="100"')+`<p class="help">${t('Rekod selepas wang benar-benar dibayar atau digunakan. App tidak memindahkan wang.')}</p>`,async f=>{await repo.fundEntry(b.dataset.uEntry,moneyInput(f.get('amount')),b.dataset.uType,f.get('title'),requestId);});});bindAll('[data-u-settings]',()=>modal(t('Paparan Utility'),Object.keys(labels).map(k=>`<label class="check-row"><input type="checkbox" name="visible" value="${k}" ${hidden.includes(k)?'':'checked'}>${t(labels[k])}</label>`).join('')+`<p class="help">${t('Tetapan ini untuk akaun anda sahaja; rekod tidak dipadam.')}</p>`,async f=>{hidden=Object.keys(labels).filter(k=>!f.getAll('visible').includes(k));localStorage.setItem('utility-hidden-'+uid()+'-'+spaceId,JSON.stringify(hidden));ctx.render();}));}
 return {start,stop,render,bind};
}
